on:
  push:
    branches:
     - "main"
  pull_request:
name: test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '>=1.18'
    - uses: actions/checkout-go@v3
    - run: go test ./... -coverprofile=coverage.out
    - name: report coverage
      uses:　k１LoW/octocov -action＠v0
